### ISSUE TITLE
aredis fails to install using pip

### ISSUE THREAD

**Issue by inytar** [NoneGG/aredis#11]
aredis is failing to install in a new environment. Trying to install it results in the following error:
```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ztxqbwm1/aredis/setup.py", line 5, in <module>
        from aredis import __version__
      File "/tmp/pip-build-ztxqbwm1/aredis/aredis/__init__.py", line 1, in <module>
        from aredis.client import StrictRedis
      File "/tmp/pip-build-ztxqbwm1/aredis/aredis/client.py", line 10, in <module>
        from aredis.commands.cluster import ClusterCommandMixin
    ImportError: No module named 'aredis.commands'
    
    ----------------------------------------
```
The reason seems to be that setup.py is loading the __version__ from init, this results in trying to load the whole package, which fails as the package is not installed yet. 

Pip version 9.0.1, aredis version 1.0.4

**Comment by NoneGG** [comment]
Thank you for reporting this problem sincerely!

I only test the setup sheet by using `python setup.py install` and that can run smoothly so i didn't expect there would be problem with `pip install`. This is my negligence. 

The bug is now fixed but pypi only allow code with the same version num be upload once, so i have to increase the version num to 1.0.5. If you don't mind, please try again to install it  by `pip install aredis`.

If you have any other problems please tell me. I will appreciate it a lot.
Thank you for your report again.

**Comment by NoneGG** [comment]
@inytar

**Comment by inytar** [comment]
Thank you for the quick response and fix! I've installed the new version from pypi without any problems.
Thanks again!

**Comment by NoneGG** [comment]
You are welcome~
