### ISSUE TITLE
Error when using subscribe

### ISSUE THREAD

**Issue by melhin** [NoneGG/aredis#28]
When i check the subscribe functionality i get an error
This is the code sample
```
        client = StrictRedisCluster(startup_nodes=[{"host": "127.0.0.1", "port": 7002}])
        sub = client.pubsub()
        await sub.subscribe("boom")
```
This is the traceback 
```

ERROR:root:  File "/home/melhin/virtualenvs/aiotest/lib/python3.5/site-packages/aredis/pool.py", line 466, in get_master_node_by_slot
    return self.nodes.slots[slot][0]
```
On further debugging i found out that 
`self.nodes.slots[slot][0] `
is the on causing the problem , mostly because 
self.nodes.slots is empty . Is there a configuration issue with my redis setting ?

**Comment by NoneGG** [comment]
@melhin 
That's my negligence, in cluster mode, nodemanager need to be initialized so that the cluster client can work well (It used to be initialized in `__init__` of connection pool, i depart it outside because it is async now ).
But i forgot to initialize it in pubsub, that causes the problem (also in pipeline, repaird in this patch as well)

It is really helpful for you to you to report the bug to me! Please allow me to add you to the [author list](http://aredis.readthedocs.io/en/latest/authors.html)
