### ISSUE TITLE
RuntimeWarning: coroutine 'PubSub.on_connect' was never awaited

### ISSUE THREAD

**Issue by qwexvf** [NoneGG/aredis#37]
Hello! i'm having a trouble implementing pub/sub with server sent events.
and i got 
```Python
/home/vagrant/.pyenv/versions/3.6.1/lib/python3.6/asyncio/coroutines.py:109: RuntimeWarning: coroutine 'PubSub.on_connect' was never awaited
  return self.gen.send(None)
```

my stream view
```Python
@app.route("/notifications")
async def notification(request):
    async def _stream(res):
        redis = aredis.StrictRedis()
        pub = redis.pubsub()
        await pub.subscribe('test')
        while True:
            message = await pub.get_message()
            if message:
                res.write(message)
            asyncio.sleep(0.001)
    return stream(_stream)
```

Any thoughts?

**Comment by NoneGG** [comment]
@qwexvf 

## explanation about the problem
There is only when place where `Pubsub.on_connect` is used.

In `Pubsub.execute_command`, `Pubsub.on_connect` is registered to the connection by `register_connect_callback` if `Pubsub.connection` is None(the attr is given None when initialized, so it is None in your case) and will be executed after connection is built.

The main purpose is to re-subscribes to any channels we were listening to when we were disconnected.

## reproduction of the problem
To reproduce the problem to find out the bug, i firstly run the [example code](https://github.com/NoneGG/aredis/blob/master/examples/pubsub.py) and it seems to run smoothly. 
So i doubt if `task` registered is run when connection is connected, so i print message and raise Error in `BaseConnection.connect` like this:

``` Python
async def connect(self):
        try:
            await self._connect()
        except Exception as exc:
            raise ConnectionError()
        # run any user callbacks. right now the only internal callback
        # is for pubsub channel/pattern resubscription
        for callback in self._connect_callbacks:
            task = callback(self)
            if isinstance(task, types.CoroutineType):
                # these code is added to prove that task is awaited in normal cases
                print('error msg')
                raise Exception
                await task
```
And the out put is:

```
/home/cm/work/aredis/env/bin/python /home/cm/work/aredis/examples/pubsub2.py
Traceback (most recent call last):
  File "/home/cm/work/aredis/examples/pubsub2.py", line 25, in <module>
    loop.run_until_complete(use_pubsub_in_thread())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/cm/work/aredis/examples/pubsub2.py", line 16, in use_pubsub_in_thread
    await pubsub.subscribe(**{'my-channel': my_handler})
  File "/home/cm/work/aredis/aredis/pubsub.py", line 157, in subscribe
    ret_val = await self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
  File "/home/cm/work/aredis/aredis/pubsub.py", line 81, in execute_command
    await self._execute(connection, connection.send_command, *args)
  File "/home/cm/work/aredis/aredis/pubsub.py", line 85, in _execute
    return await command(*args)
  File "/home/cm/work/aredis/aredis/connection.py", line 463, in send_command
error msg
    await self.connect()
  File "/home/cm/work/aredis/aredis/connection.py", line 405, in connect
    raise Exception
Exception
sys:1: RuntimeWarning: coroutine 'PubSub.on_connect' was never awaited
```
The situation is now like what you report, so i think your problem is caused by an unknown error. 
If you don't mind, could you give me more detailed error info?  That will be helpful to me to locate the real problem, thanks~

**Comment by qwexvf** [comment]
Hello! thank you for checking this out!
i tried to look for more details error but its so strange lol.
i'm having another issue atm,

```Python
2017-07-02 10:07:40 - (network)[INFO][('192.168.33.1:52707',)]: GET b'/notifications'  408 22
2017-07-02 10:07:40 - (sanic)[ERROR]: Transport closed @ ('192.168.33.1', 52707) and exception experienced during error handling
2017-07-02 10:07:40 - (sanic)[DEBUG]: Exception:
Traceback (most recent call last):
  File "/vagrant/projects/jet/backend_ver2/venv/lib/python3.6/site-packages/aredis/connection.py", line 301, in read_response
    buffer = await self._stream.read(self._read_size)
  File "/home/vagrant/.pyenv/versions/3.6.1/lib/python3.6/asyncio/streams.py", line 628, in read
    yield from self._wait_for_data('read')
  File "/home/vagrant/.pyenv/versions/3.6.1/lib/python3.6/asyncio/streams.py", line 458, in _wait_for_data
    yield from self._waiter
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vagrant/projects/jet/backend_ver2/venv/lib/python3.6/site-packages/sanic/server.py", line 240, in stream_response
    self.request.version, keep_alive, self.request_timeout)
  File "/vagrant/projects/jet/backend_ver2/venv/lib/python3.6/site-packages/sanic/response.py", line 144, in stream
    await self.streaming_fn(self)
  File "/vagrant/projects/jet/backend_ver2/jet/__init__.py", line 47, in _stream
    while True:
  File "/vagrant/projects/jet/backend_ver2/venv/lib/python3.6/site-packages/aredis/pubsub.py", line 182, in get_message
    response = await self.parse_response(block=False)
  File "/vagrant/projects/jet/backend_ver2/venv/lib/python3.6/site-packages/aredis/pubsub.py", line 107, in parse_response
    return await self._execute(connection, connection.read_response)
  File "/vagrant/projects/jet/backend_ver2/venv/lib/python3.6/site-packages/aredis/pubsub.py", line 85, in _execute
    return await command(*args)
  File "/vagrant/projects/jet/backend_ver2/venv/lib/python3.6/site-packages/aredis/connection.py", line 428, in read_response
    response = await exec_with_timeout(self._parser.read_response(), self._stream_timeout, loop=self.loop)
  File "/vagrant/projects/jet/backend_ver2/venv/lib/python3.6/site-packages/aredis/connection.py", line 34, in exec_with_timeout
    return await asyncio.wait_for(coroutine, timeout, loop=loop)
  File "/home/vagrant/.pyenv/versions/3.6.1/lib/python3.6/asyncio/tasks.py", line 333, in wait_for
    return (yield from fut)
  File "/vagrant/projects/jet/backend_ver2/venv/lib/python3.6/site-packages/aredis/connection.py", line 305, in read_response
    (e.args,))
aredis.exceptions.ConnectionError: Error while reading from stream: ()

[2017-07-02 10:07:55 +0000] [19005] [INFO] Handling signal: winch
```

I don't know that do haha..
but i understood that the examples are working fine! so its something about my application.
thank you for helping me out.

**Comment by NoneGG** [comment]
I am not sure, according to the error info, an error take place when `HiredisParser` tried to read from the `StreamReader` (asyncio). To handle the unknown exception, i will collect the error info and raise a ConnectionError instead ( but there seems to be no error args in this case)

I think it may be the network problem, can this error and the former error you post be reproduced steadily?

**Comment by NoneGG** [comment]
@qwexvf 
## about the first problem
I am not so familiar with sanic(it seems to be a nice framework), so i tried to launch stream view with the most common method provided by the official doc. 

I use aredis 1.0.8 and the code below works fine (i add a statement to publish message), the server runs on 0.0.0.0:8000 and i use `curl http://0.0.0.0:8000/notifications` to call the api.

```Python
import asyncio
import aredis
from sanic.app import Sanic
from sanic.response import json, stream

app = Sanic()

@app.route("/")
async def test(request):
    return json({"hello": "world"})

@app.route("/notifications")
async def notification(request):
    async def _stream(res):
        redis = aredis.StrictRedis()
        pub = redis.pubsub()
        await pub.subscribe('test')
        while True:
            await redis.publish('test', 111)
            message = await pub.get_message()
            if message:
                res.write(message)
            asyncio.sleep(0.001)
    return stream(_stream)

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
```

I am not sure why the similar code have problem in your local env(may it be caused by network?)
If you don't mind, could you give me code about the second problem?

**Comment by qwexvf** [comment]
Hello, The first problem seems to be fixed and working but not sure what was wrong.
i was trying to combine EventSource with redis pub/sub but seems to be too complicated.
ill stick with webosckets for now..

But Thank you so much for all that information. really helpful feedbacks.

**Comment by NoneGG** [comment]
Don't mind~ Your bug report is important. Working out problem raised by user can make aredis better.

The second problem is caused by `concurrent.futures._base.CancelledError` raised during `StreamReader.read`, and i read related code and doc, `CancelledError` will only be raised after futures's state is set to `_CANCELLED`(from asyncio.futures) it seems to be a normal operation done by event loop.
And then i noticed the WINCH signal handling in the end of your log. Then i look for signal handling code in sanic and find this:
```Python
def init_signals(self):
        # Set up signals through the event loop API.

        self.loop.add_signal_handler(signal.SIGQUIT, self.handle_quit,
                                     signal.SIGQUIT, None)

        self.loop.add_signal_handler(signal.SIGTERM, self.handle_exit,
                                     signal.SIGTERM, None)

        self.loop.add_signal_handler(signal.SIGINT, self.handle_quit,
                                     signal.SIGINT, None)

        self.loop.add_signal_handler(signal.SIGWINCH, self.handle_winch,
                                     signal.SIGWINCH, None)

        self.loop.add_signal_handler(signal.SIGUSR1, self.handle_usr1,
                                     signal.SIGUSR1, None)

        self.loop.add_signal_handler(signal.SIGABRT, self.handle_abort,
                                     signal.SIGABRT, None)

        # Don't let SIGTERM and SIGUSR1 disturb active requests
        # by interrupting system calls
        signal.siginterrupt(signal.SIGTERM, False)
        signal.siginterrupt(signal.SIGUSR1, False)
```
`add_signal_handler` is realized by event loop. The cancel operation seems to be caused by the signal?
I am not sure because the signal ignore by `self.handle_winch` inherit from gunicorn like this(if you are not using the newest version and work on OpenBSD, the crash refered may be the problem indeed)
```Python
def handle_winch(self, sig, fname):
        # Ignore SIGWINCH in worker. Fixes a crash on OpenBSD.
        self.log.debug("worker: SIGWINCH ignored.")
```
An easy way to find out the truth whether the problem is that is to set your log level to DEBUG and then the log will be shown 0- 0

**Comment by qwexvf** [comment]
This issue is really weird.... i noticed that pub/sub is working.even if this is error happens.
```2017-08-05 14:36:01 - (network)[INFO][192.168.33.1:64044]: OPTIONS http://192.168.33.10:5000/api/me/post/replies  200 0
<CoroWrapper PubSub.on_connect() running at /home/vagrant/.pyenv/versions/env361/lib/python3.6/site-packages/aredis/pubsub.py:47, created at /home/vagrant/.pyenv/versions/3.6
.1/lib/python3.6/asyncio/coroutines.py:84> was never yielded from
Coroutine object created at (most recent call last):
  File "server.py", line 5, in <module>
    app.run(host=address, port=5000, debug=True)
  File "/home/vagrant/.pyenv/versions/env361/lib/python3.6/site-packages/sanic/app.py", line 595, in run
    serve(**server_settings)
  File "/home/vagrant/.pyenv/versions/env361/lib/python3.6/site-packages/sanic/server.py", line 527, in serve
    loop.run_forever()
  File "/home/vagrant/.pyenv/versions/3.6.1/lib/python3.6/asyncio/coroutines.py", line 125, in send
    return self.gen.send(value)
  File "/vagrant/projects/jet/jet-backend/app/app.py", line 44, in feed
    await pub.subscribe('test')
  File "/home/vagrant/.pyenv/versions/3.6.1/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/home/vagrant/.pyenv/versions/env361/lib/python3.6/site-packages/aredis/pubsub.py", line 157, in subscribe
    ret_val = await self.execute_command('SUBSCRIBE', *iterkeys(new_channels))
  File "/home/vagrant/.pyenv/versions/3.6.1/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/home/vagrant/.pyenv/versions/env361/lib/python3.6/site-packages/aredis/pubsub.py", line 81, in execute_command
    await self._execute(connection, connection.send_command, *args)
  File "/home/vagrant/.pyenv/versions/3.6.1/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/home/vagrant/.pyenv/versions/env361/lib/python3.6/site-packages/aredis/pubsub.py", line 85, in _execute
    return await command(*args)
  File "/home/vagrant/.pyenv/versions/3.6.1/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/home/vagrant/.pyenv/versions/env361/lib/python3.6/site-packages/aredis/connection.py", line 461, in send_command
    await self.connect()
  File "/home/vagrant/.pyenv/versions/3.6.1/lib/python3.6/asyncio/coroutines.py", line 109, in __next__
    return self.gen.send(None)
  File "/home/vagrant/.pyenv/versions/env361/lib/python3.6/site-packages/aredis/connection.py", line 402, in connect
    task = callback(self)
  File "/home/vagrant/.pyenv/versions/3.6.1/lib/python3.6/asyncio/coroutines.py", line 84, in debug_wrapper
    return CoroWrapper(gen, None)
/home/vagrant/.pyenv/versions/3.6.1/lib/python3.6/asyncio/coroutines.py:109: RuntimeWarning: coroutine 'PubSub.on_connect' was never awaited
  return self.gen.send(None)```

**Comment by NoneGG** [comment]
@qwexvf Thank you for the detailed info.
Related code is here and it is only used by pubsub(for now) to register a callback when connection is connected and then re-subscribe to any channels and patterns previously subscribed to.

The reason why pubsub can still run smoothly because it is a warning and only the re-subscription is influenced(which may be not so obvious).

```Python
async def connect(self):
        try:
            await self._connect()
        except Exception as exc:
            raise ConnectionError()
        # run any user callbacks. right now the only internal callback
        # is for pubsub channel/pattern resubscription
        for callback in self._connect_callbacks:
            # this is the coroutine which is not awaited
            task = callback(self)
            if isinstance(task, types.CoroutineType):
                await task
```
It is weird that `Pubsub.on_connect` is not awaited, i will check it now.

**Comment by NoneGG** [comment]
@qwexvf 
I think i can reproduce the problem steadily and nearly find the reason now.

## why warning is not raised in my dev env?
In python3.5, the warning will not be raised even in debug mode of sanic(That's why i can't reproduce the error in former cases. It's my fault to debug in wrong direction. The bug, as said before, is disguised indeed, it is a warning and won't stop your program running)

And after i do everything i can do, finally i notice that your code is running under python3.6. And then with the same code can the bug be reproduced steadily.

## true reason
The problem is caused by the difference of `types.CoroutineType` & `asyncio.coroutines.CoroWrapper`

In official doc, `CoroutinType` is described like: `The type of coroutine objects, created by async def functions.`

So i used it to check if callback of the connection is a coroutine and decide whether should aredis await it.
But actually the coroutine is instance of `asyncio.coroutines.CoroWrapper`. And the callback is never successful before, and my test doesn't find that out.

## how to continue your work
Bug is fixed and pushed to master branch and the warning is not raised in both python 3.5 & 3.6 environment (in my dev environment, lol)
If you don't mind, could you try the new version by command?
`pip install git+https://github.com/NoneGG/aredis`

**Comment by qwexvf** [comment]
Hello, i'm sorry i should have left my python version.
And its working very nice! thank you for your support.

i'm going to learn more about async/await stuff i'm too newbie....

**Comment by NoneGG** [comment]
It's my fault, actually your python version is left in your log but i ignored it.
がんばって！
If you have other problems about aredis, please tell me and i will solve them as soon as possible~

**Comment by ahopkins** [comment]
@qwexvf Thanks!

I was also seeing the error:

`RuntimeWarning: coroutine 'PubSub.on_connect' was never awaited return self.gen.send(None)`

Installing the latest version using `pip install git+https://github.com/NoneGG/aredis` (I moved from v 1.0.9 to 1.1.0) fixed the problem.
