### ISSUE TITLE
maybe it should wait instead of raise an error if reached the max connection limit

### ISSUE THREAD

**Issue by myrfy001** [NoneGG/aredis#51]
I'm now running aredis  connecting to a cluster with 12 node, and the client side has more than 50 machines, and about 200 client process,  So, the total connection number is very large.

And because we use asyncio, a lot of tasks are running at the same time. When a request peek comes,  `Too Many Connections` error often occurs. 

I don't want to increase the connection pool size. We use asyncio so we can make a task sleep and waiting for connections.

It's only a suggestion because a retry can also be done by user insted of aredis library.

**Comment by NoneGG** [comment]
Sure, i will think about it and give a response recently~ Thank you for your suggestion

**Comment by NoneGG** [comment]
@myrfy001 
I consider about your suggestion last night. 

I think the client should not decide the behavior of program instead of user when too many connections are built. User's program can catch the exception and custom their code to handle the error (they may need the coroutine to do something else instead of sleeping)

So i can't let the task wait in my client silently.
Thank you for your suggestion all the same. 
By the way, i think the size of connection pool should be increased.
Even the cluster pool should be increased if there are too much load on redis node. Usually keys are distributed uniformly in cluster if you don't hash them to a single slot by hash tags and addition of nodes will also decrease the load of each single node in cluster.

**Comment by NoneGG** [comment]
@myrfy001 May i close this issue?
