### ISSUE TITLE
Distributed lock for Redis Cluster

### ISSUE THREAD

**Issue by semirook** [NoneGG/aredis#55]
Hi!

It would be very useful to have distributed lock support for the cluster in your awesome library. It's very common to have Redis cluster on production and Redis-related logic is just broken with >1 instance of consumer, for example. None of current drivers have such a feature.

Thank you.

**Comment by NoneGG** [comment]
@semirook 
Actually i am also considering about this problem recently. The distributed lock function is assumed to be finish in coming release, but i find some problem about it. 

The official solution provided by redis team is [redlock](https://redis.io/topics/distlock). 
But that is not so suitable for redis cluster because the same keys will be hashed to the same slot(thus the same master node). Even you can use hash tag to force lock key to be hashed to different nodes, you can not make sure slots are on different node(slot may be migrated among nodes). 
How about believe in single master node? That can't be trusted either. 
Imagine a situation:
1. client1 acquire lock on master1
2. master1 sync change to slave1
3. master1 is killed before sync succeeded
4. slave1 becomes master1(new) without lock acquired
5. client2 acquire lock on master1(new), the resource is not proteceted

According to my research on other redis related package. redisson(a java package) give a solution by bind different key to a lock, which leaves the hash problem to users.

Do you have any idea or advice about the distributed lock using redis cluster?

**Comment by semirook** [comment]
Thank you for quick response. Described problem is clear for me and I'll think about it too.

**Comment by NoneGG** [comment]
If you have idea bout it please tell me, i need someone to discuss about the issue indeed.
I will leave this issue open~

**Comment by NoneGG** [comment]
@semirook 
About the hash problem, i have got three ideas.

## idea1:
Trust single node and its fail-over, set lock key in master node and then use cluster `readonly` mode to read lock key from slave node (may redlock algorithm be used) to confirm sync between master and slave is successful(in this way the lock is available until master node and all its slaves are down)

## idea2:
Generate specific key according to lock key given by user according to simple rule, and then use `setslot` to make sure most of node has generated key, the rest part is the redlock's job. 

## idea3:
Similar to idea2, but directly generating key by rule which can make them hashed to different slot and different node(it is hard, and it is needed to make sure the same output is given with the same input by different client process)

All these ideas can not handle the situation if most of the lock keys are migrated.
How do you think about that?

**Comment by NoneGG** [comment]
@semirook 
Finally i implement the distributed lock according to the first idea. If you don't mind, could you please help me to review the changes at: [commit](https://github.com/NoneGG/aredis/commit/50d1d539b34d69afcea412d9dd07f6cbb150adf7)?

Although i have thought several extreme situation, i am still worried about consistency and efficiency of the lock.

**Comment by semirook** [comment]
Anyway you understand all of that corner cases better. I'll take a look, sure.

**Comment by NoneGG** [comment]
@semirook `ClusterLock` is merged and will be available in next release~
