### ISSUE TITLE
API reference on readthedocs

### ISSUE THREAD

**Issue by halicki** [NoneGG/aredis#67]
Hello everyone!
Could the [_API reference_ page on readthedocs](http://aredis.readthedocs.io/en/latest/api_reference.html)  include the real description the API? At the moment it has no content - only modules hedlines.
Sincerely
Arek

**Comment by NoneGG** [comment]
Hi @halicki ~
For now the API reference part of doc is generated automatically by sphinx and not so detailed. Since you can find most API description in [redis command reference](https://redis.io/commands) only something different or important is referred in doc specially.
You can ask here / post a new issue / read [redis command reference](https://redis.io/commands) If you have any problem about the API.

**Comment by halicki** [comment]
Hey @NoneGG!
Thank you for your response. I don't have any problem with any specific command. Just wanted to make documentation on readthedocks not having so many empty places. Having said that, maybe it would be a good idea to remove those parts from Sphinks generated docs. We should provide a valuable info for our users or skip a doc page at all.
Cheers!
Arek

**Comment by NoneGG** [comment]
@halicki 
You are right, i will try to optimize this part of doc~
Thank you for your advice.

**Comment by NoneGG** [comment]
@halicki 
Thank you again for your advice~
New issue is welcomed if you have any other advice.
