### ISSUE TITLE
hi,I think there is an optimization place here.

### ISSUE THREAD

**Issue by BlingBlingdevelopers** [NoneGG/aredis#88]
i use  ` xreadgroup`  get a `dict` type
but when i use `xclaim` i get a type same as redis-native --get a `list` type,
so do you solve it ?

**Comment by NoneGG** [comment]
@BlingBlingdevelopers 
Thank you for your advice firstly~
Since `XCLAIM` command is not released officially (i can only find it in [streams-intro](https://redis.io/topics/streams-intro) instead of commands manual), i am not so sure whether the api is stable yet. And the response parser is not stable yet. I will think about your advice

**Comment by BlingBlingdevelopers** [comment]
Ok, I am too anxious, haha.
